spring:
  profiles:
    active: dev
  application:
    name: TEMPLATE-BACKEND
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/invest
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  jwt:
    auth:
      convert:
        resource-id: invest-backend
        principal-attribute: preferred_username


